// 候補一覧（元の candidateGroups をそのまま移動）
window.CANDIDATE_GROUPS = [
  {
    id: "q1",
    name: "画質・スタイル",
    items: [
      "masterpiece",
      "best quality",
      "ultra-detailed",
      "highly detailed",
      "highres",
      "ultra highres",
      "sharp focus",
      "crisp lines",
      "finely detailed",
      "vivid colors",
      "soft shading",
      "cel shading",
      "anime style",
      "manga style",
      "semi-realistic",
      "painterly",
      "watercolor style",
      "oil painting style",
      "sketch",
      "lineart",
      "HDR",
      "8k",
      "very aesthetic",
      "detailed background",
      "perfect lighting",
      "stunning details"
    ]
  },
  {
    id: "q2",
    name: "人物・キャラクター",
    items: [
      "girl",
      "boy",
      "1girl",
      "1boy",
      "2girls",
      "2boys",
      "group",
      "solo",
      "chibi",
      "kemonomimi",
      "elf",
      "demon girl",
      "angel",
      "witch",
      "warrior",
      "mage",
      "knight",
      "shrine maiden",
      "vampire",
      "young",
      "teen",
      "adult",
      "slim",
      "athletic",
      "petite",
      "curvy"
    ]
  },
  {
    id: "q3",
    name: "顔・表情",
    items: [
      "looking at viewer",
      "looking away",
      "profile view",
      "closed eyes",
      "winking",
      "smiling",
      "laughing",
      "frowning",
      "sad",
      "crying",
      "determined",
      "embarrassed",
      "blushing",
      "serious",
      "sleepy",
      "surprised",
      "expressive eyes",
      "sharp eyes",
      "shining eyes",
      "glowing eyes"
      "blush"
    ]
  },
  {
    id: "q4",
    name: "髪型",
    items: [
      "long hair",
      "short hair",
      "medium hair",
      "very long hair",
      "bob cut",
      "ponytail",
      "side ponytail",
      "twintails",
      "braid",
      "side braid",
      "bun hairstyle",
      "messy hair",
      "wavy hair",
      "curly hair",
      "straight hair"
    ]
  },
  {
    id: "q5",
    name: "髪色",
    items: [
      "black hair",
      "brown hair",
      "blonde hair",
      "silver hair",
      "white hair",
      "red hair",
      "pink hair",
      "blue hair",
      "green hair",
      "purple hair",
      "gradient hair",
      "multicolored hair"
    ]
  },
  {
    id: "q6",
    name: "目",
    items: [
      "blue eyes",
      "red eyes",
      "green eyes",
      "golden eyes",
      "purple eyes",
      "heterochromia",
      "big eyes",
      "narrow eyes",
      "sparkling eyes",
      "glowing eyes"
    ]
  },
  {
    id: "q7",
    name: "服装（カジュアル）",
    items: [
      "casual wear",
      "T-shirt",
      "hoodie",
      "sweater",
      "coat",
      "jacket",
      "jeans",
      "skirt",
      "shorts"
    ]
  },
  {
    id: "q8",
    name: "服装（制服・衣装）",
    items: [
      "school uniform",
      "sailor uniform",
      "blazer uniform",
      "maid outfit",
      "nurse outfit",
      "military uniform",
      "suit",
      "dress",
      "wedding dress",
      "kimono",
      "yukata",
      "hakama",
      "armor"
    ]
  },
  {
    id: "q9",
    name: "アクセサリー",
    items: [
      "ribbon",
      "hairband",
      "hair ornament",
      "hat",
      "beret",
      "eyeglasses",
      "sunglasses",
      "scarf",
      "gloves",
      "stockings",
      "thighhighs",
      "boots",
      "sneakers",
      "necklace",
      "earrings"
    ]
  },
  {
    id: "q10",
    name: "ポーズ",
    items: [
      "standing",
      "sitting",
      "lying down",
      "jumping",
      "running",
      "walking",
      "dynamic pose",
      "action pose",
      "crossed arms",
      "hand on hip",
      "peace sign",
      "looking back",
      "holding weapon",
      "reading a book",
      "reaching out",
      "lying",
      "on back",
      "on stomach"
    ]
  },
  {
    id: "q11",
    name: "カメラ・構図",
    items: [
      "close-up",
      "bust shot",
      "upper body",
      "full body",
      "from above",
      "from below",
      "wide shot",
      "extreme close-up",
      "Dutch angle",
      "POV",
      "back view",
      "side view",
      "medium shot"
    ]
  },
  {
    id: "q12",
    name: "照明・雰囲気",
    items: [
      "soft lighting",
      "strong shadows",
      "dramatic lighting",
      "rim light",
      "backlight",
      "glow",
      "warm lighting",
      "cool lighting",
      "sunset lighting",
      "golden hour",
      "cinematic lighting",
      "volumetric lighting",
      "silhouette",
      "glowing light",
      "night lighting"
    ]
  },
  {
    id: "q13",
    name: "背景・環境",
    items: [
      "cityscape",
      "street at night",
      "cafe",
      "classroom",
      "school corridor",
      "rooftop",
      "park",
      "forest",
      "mountain",
      "beach",
      "seaside",
      "shrine",
      "temple",
      "traditional Japanese room",
      "library",
      "laboratory",
      "futuristic city",
      "cyberpunk city",
      "night sky",
      "cherry blossoms",
      "snow",
      "autumn leaves",
      "summer festival",
      "fireworks",
      "fantasy landscape"
    ]
  },
  {
    id: "q14",
    name: "エフェクト・演出",
    items: [
      "particles",
      "sparkles",
      "glowing particles",
      "magic circle",
      "aura",
      "smoke",
      "fog",
      "rain",
      "snowfall",
      "lens flare",
      "floating particles"
    ]
  },
  {
    id: "q15",
    name: "ネガティブ（共通）",
    items: [
      "lowres",
      "blurry",
      "jpeg artifacts",
      "watermark",
      "bad anatomy",
      "bad hands",
      "bad proportions",
      "extra fingers",
      "missing fingers",
      "malformed limbs",
      "fused fingers",
      "missing limbs",
      "deformed",
      "out of focus",
      "overexposed",
      "underexposed",
      "grainy",
      "noisy",
      "duplicate",
      "worst quality"
    ]
  },
  /* ===== NSFW向けカテゴリ ===== */
  {
    id: "n1",
    name: "NSFW：服装・露出",
    items: [
      "nsfw",
      "suggestive",
      "suggestive pose",
      "revealing clothes",
      "tight clothes",
      "skin-tight",
      "cleavage",
      "deep cleavage",
      "open shirt",
      "unbuttoned shirt",
      "off-shoulder",
      "bare shoulders",
      "bare back",
      "crop top",
      "short skirt",
      "miniskirt",
      "thighhighs",
      "garter belt",
      "stockings",
      "lace stockings",
      "lingerie",
      "underwear",
      "bikini",
      "micro bikini",
      "swimsuit",
      "wet clothes",
      "see-through clothes"
    ]
  },
  {
    id: "n2",
    name: "NSFW：体の強調",
    items: [
      "curvy body",
      "voluptuous",
      "busty",
      "slender body",
      "soft body",
      "smooth skin",
      "shiny skin",
      "glossy skin",
      "narrow waist",
      "wide hips",
      "emphasized thighs",
      "thick thighs"
    ]
  },
  {
    id: "n3",
    name: "NSFW：ポーズ・雰囲気",
    items: [
      "seductive",
      "seductive smile",
      "teasing smile",
      "playful pose",
      "alluring pose",
      "shy pose",
      "embarrassed",
      "blushing",
      "lying on bed",
      "on the bed",
      "bedroom background",
      "intimate atmosphere",
      "romantic lighting",
      "soft bedroom lighting"
    ]
  },
  {
    id: "n4",
    name: "NSFW：ネガティブ",
    items: [
      "unrealistic body",
      "deformed chest",
      "strange shadows on skin",
      "overexposed skin",
      "harsh lighting"
    ]
  }
];
